bus-reservation-system-in-django/myproject/myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myapp'

urlpatterns = [
    path('', views.home, name="home"),
    path('findbus', views.findbus, name="findbus"),
    path('bookings', views.bookings, name="bookings"),
    path('cancellings/', views.cancellings, name="cancellings"),
    path('seebookings', views.seebookings, name="seebookings"),
    path('signup', views.signup, name="signup"),
    path('signin', views.signin, name="signin"),
    path('signout', views.signout, name="signout"),
    path('aboutus', views.aboutus, name="aboutus"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bus-reservation-system-in-django/myproject/myproject/urls.py
from django.urls import path,include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

bus-reservation-system-in-django/myproject/myapp/models.py
# Create your models here.
from django.db import models


# Create your models here.

class Bus(models.Model):
    bus_name = models.CharField(max_length=30)
    source = models.CharField(max_length=30)
    dest = models.CharField(max_length=30)
    nos = models.DecimalField(decimal_places=0, max_digits=2)
    rem = models.DecimalField(decimal_places=0, max_digits=2)
    price = models.DecimalField(decimal_places=2, max_digits=6)
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return self.bus_name


class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    email = models.EmailField()
    name = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

    def __str__(self):
        return self.email


class Book(models.Model):
    BOOKED = 'B'
    CANCELLED = 'C'

    TICKET_STATUSES = ((BOOKED, 'Booked'),
                       (CANCELLED, 'Cancelled'),)
    email = models.EmailField()
    name = models.CharField(max_length=30)
    userid = models.DecimalField(decimal_places=0, max_digits=2)
    busid = models.DecimalField(decimal_places=0, max_digits=2)
    bus_name = models.CharField(max_length=30)
    source = models.CharField(max_length=30)
    dest = models.CharField(max_length=30)
    nos = models.DecimalField(decimal_places=0, max_digits=2)
    price = models.DecimalField(decimal_places=2, max_digits=6)
    transaction_id = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateField()
    time = models.TimeField()
    transaction_image = models.ImageField(
        upload_to='transaction_images/', default='default_image.jpg')

    status = models.CharField(choices=TICKET_STATUSES,
                              default=BOOKED, max_length=2)

    def __str__(self):
        return self.email

bus-reservation-system-in-django/myproject/myapp/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model

)

User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email address')
    email2 = forms.EmailField(label='Confirm Email')
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'email2',
            'password'
        ]

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Emails must match")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError(
                "This email has already been registered")
        return super(UserRegisterForm, self).clean(*args, **kwargs)

bus-reservation-system-in-django/myproject/myapp/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from decimal import Decimal

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import User, Bus, Book
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import UserLoginForm, UserRegisterForm
from django.contrib.auth.decorators import login_required
from decimal import Decimal


def home(request):
    if request.user.is_authenticated:
        return render(request, 'myapp/home.html')
    else:
        return render(request, 'myapp/signin.html')


@login_required(login_url='myapp:signin')
def findbus(request):
    context = {}
    if request.method == 'POST':
        source_r = request.POST.get('source')
        dest_r = request.POST.get('destination')
        date_r = request.POST.get('date')
        bus_list = Bus.objects.filter(
            source=source_r, dest=dest_r, date=date_r)
        if bus_list:
            return render(request, 'myapp/list.html', locals())
        else:
            context["error"] = "Sorry no buses availiable"
            return render(request, 'myapp/findbus.html', context)
    else:
        return render(request, 'myapp/findbus.html')


@login_required(login_url='signin')
def bookings(request):
    context = {}
    if request.method == 'POST':
        id_r = request.POST.get('bus_id')
        seats_r = int(request.POST.get('no_seats'))
        transaction_id_r = request.POST.get('itransaction_id')
        transaction_image_r = request.FILES.get(
            'itransaction_image')  # Get the uploaded image

        bus = Bus.objects.get(id=id_r)
        if bus:
            if bus.rem > int(seats_r):
                name_r = bus.bus_name
                cost = int(seats_r) * bus.price
                source_r = bus.source
                dest_r = bus.dest
                nos_r = Decimal(bus.nos)
                price_r = bus.price
                date_r = bus.date
                time_r = bus.time
                username_r = request.user.username
                email_r = request.user.email
                userid_r = request.user.id
                rem_r = bus.rem - seats_r
                Bus.objects.filter(id=id_r).update(rem=rem_r)

                # Save the uploaded image to a specific location
                fs = FileSystemStorage()
                filename = fs.save(transaction_image_r.name,
                                   transaction_image_r)
                uploaded_image_url = fs.url(filename)

                book = Book.objects.create(name=username_r, email=email_r, userid=userid_r, bus_name=name_r,
                                           source=source_r, busid=id_r,
                                           dest=dest_r, price=price_r, nos=seats_r, date=date_r, time=time_r, transaction_id=transaction_id_r,
                                           transaction_image=uploaded_image_url, status='BOOKED')

                print('------------book id-----------', book.id)
                return render(request, 'myapp/bookings.html', locals())
            else:
                context["error"] = "Sorry, select a fewer number of seats"
                return render(request, 'myapp/findbus.html', context)

    else:
        return render(request, 'myapp/findbus.html')


@login_required(login_url='signin')
def cancellings(request):
    context = {}
    if request.method == 'POST':
        id_r = request.POST.get('bus_id')
        # seats_r = int(request.POST.get('no_seats'))

        try:
            book = Book.objects.get(id=id_r)
            bus = Bus.objects.get(id=book.busid)
            rem_r = bus.rem + book.nos
            Bus.objects.filter(id=book.busid).update(rem=rem_r)
            # nos_r = book.nos - seats_r
            Book.objects.filter(id=id_r).update(status='CANCELLED')
            Book.objects.filter(id=id_r).update(nos=0)
            return redirect('myapp:seebookings')
        except Book.DoesNotExist:
            context["error"] = "Sorry You have not booked that bus"
            return render(request, 'myapp/error.html', context)
    else:
        return render(request, 'myapp/findbus.html')


@login_required(login_url='signin')
def seebookings(request, new={}):
    context = {}
    id_r = request.user.id
    book_list = Book.objects.filter(userid=id_r)
    if book_list:
        return render(request, 'myapp/booklist.html', locals())
    else:
        context["error"] = "Sorry no buses booked"
        return render(request, 'myapp/findbus.html', context)


def signup(request):
    context = {}
    if request.method == 'POST':
        name_r = request.POST.get('name')
        email_r = request.POST.get('email')
        password_r = request.POST.get('password')
        profile_picture_r = request.FILES.get('profile_picture')

        user = User.objects.create_user(name_r, email_r, password_r)
        if user:
            if profile_picture_r:
                user.profile_picture = profile_picture_r
                user.save()

            login(request, user)
            return redirect('myapp:home')

        else:
            context["error"] = "Provide valid credentials"
            return render(request, 'myapp/signup.html', context)
    else:
        return render(request, 'myapp/signup.html', context)


def signin(request):
    context = {}
    if request.method == 'POST':
        name_r = request.POST.get('name')
        password_r = request.POST.get('password')
        user = authenticate(request, username=name_r, password=password_r)
        if user:
            login(request, user)
            # username = request.session['username']
            context["user"] = name_r
            context["id"] = request.user.id
            return redirect('myapp:home')

            # return HttpResponseRedirect('success')
        else:
            context["error"] = "Provide valid credentials"
            return render(request, 'myapp/signin.html', context)
    else:
        context["error"] = "You are not logged in"
        return render(request, 'myapp/signin.html', context)


def signout(request):
    context = {}
    logout(request)
    context['error'] = "You have been logged out"
    return render(request, 'myapp/signin.html', context)


def success(request):
    context = {}
    context['user'] = request.user
    return render(request, 'myapp/success.html', context)


def aboutus(request):
    return render(request, 'myapp/aboutus.html')

bus-reservation-system-in-django/myproject/myapp/templates/myapp/aboutus.html
{% extends 'myapp/base.html' %} {% load static %} {% block content %}
<style>
  body {
    background-color: #f8f9fa;
  }
</style>

<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-6">
      <div class="card border-0 shadow">
        <img
          src="{% static 'myapp/Buslogo.png' %}"
          class="card-img-top"
          alt="About Us"
        />
        <div class="card-body">
          <h2 class="card-title">About Us</h2>
          <p class="card-text">
            At FM Bus, we are committed to providing safe, reliable and
            comfortable transportation for all our passengers. Since our
            founding in 2020, we have worked tirelessly to exceed our customers'
            expectations and build a reputation as one of the most trusted bus
            companies in the industry.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

bus-reservation-system-in-django/myproject/myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />

    <!-- Set the page title -->
    <title>{% block title %}FmBus Ticket Booking{% endblock %}</title>

    <!-- Link to custom CSS file -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'myapp/style.css' %}"
    />

    <!-- Link to Bootstrap CSS file -->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    />

    <!-- Include Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"></script>

    <!-- Link to Font Awesome CSS file -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />

    <!-- Custom inline CSS style for the footer -->
    <style>
      footer {
        color: ;
      }
    </style>
  </head>

  <body>
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">
          <!-- Company logo -->
          <img
            src="{% static 'myapp/Logo.jpg' %}"
            alt="Company Logo"
            class="logo"
          />
          <span class="navbar-brand-text">FM Bus Ticket Booking</span>
          <!-- Navbar text -->
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
          <!-- Toggler icon for mobile navigation -->
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <!-- Navbar items -->
          <ul class="navbar-nav mr-auto">
            <!-- Left-aligned navbar items -->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:findbus' %}">Find Bus</a>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:seebookings' %}">See Bookings</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:aboutus' %}">About Us</a>
              </li>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <!-- Right-aligned navbar items -->
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:signout' %}">Sign Out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:signin' %}">Sign In</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:signup' %}">Sign Up</a>
              </li>

            {% endif %}
         
          </ul>
          <li class="nav-item">
            <span class="navbar-text">
              {% if user.is_authenticated %}
                Welcome, {{ user.username }}
              {% endif %}
            </span>
          </li>
        </ul>
        </div>
      </div>
    </nav>
   
    {% block content %} {% endblock %}

    <!-- Footer contents -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="centered-section">
            <!-- Contact Us section -->
            <h3>Contact Us</h3>
            <p>
              <i class="fas fa-map-marker-alt"></i> Addisu Gebeya, Addis Ababa,
              Ethiopia
            </p>
            <p>
              <i class="fas fa-map-marker-alt"></i> Nigus Teklehaymanot Square,
              Debre Markos, Ethiopia
            </p>
            <p>
              <i class="far fa-envelope"></i> Email: fmbustransport@gmail.com
            </p>
            <p><i class="fas fa-phone"></i> Phone: +251905464646</p>
            <br />
            <br />
            <!-- Follow Us section -->
            <h3>Follow Us</h3>
            <ul class="list-inline">
              <li class="list-inline-item">
                <a
                  href="https://www.facemyapp.com/profile.php?id=100064040314976&mibextid=ZbWKwL"
                  ><i class="fab fa-facemyapp"></i
                ></a>
                <!-- Facemyapp icon link -->
              </li>
              <li class="list-inline-item">
                <a href="#"><i class="fab fa-twitter"></i></a>
                <!-- Twitter icon link -->
              </li>
              <li class="list-inline-item">
                <a href="#"><i class="fab fa-instagram"></i></a>
                <!-- Instagram icon link -->
              </li>
              <li class="list-inline-item">
                <a href="#"><i class="fab fa-linkedin"></i></a>
                <!-- LinkedIn icon link -->
              </li>
              <li class="list-inline-item">
                <a href="#"><i class="fab fa-telegram"></i></a>
                <!-- Telegram icon link -->
              </li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <p class="text-center">
              &copy; 2023 FmBusTransport. All rights reserved.
            </p>
          </div>
        </div>
      </div>
    </footer>
    <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
crossorigin="anonymous"></script>
  </body>
</html>

bus-reservation-system-in-django/myproject/myapp/templates/myapp/booklist.html
{% extends 'myapp/base.html' %} {% block content %}
<h3>{{msg}}</h3>
<h2>List of buses</h2>
<table class="table table-striped">
  <thead style="background-color: blue; color: white">
    <td>BOOKING ID</td>
    <td>USER NAME</td>
    <td>BUS NAME</td>
    <td>SOURCE</td>
    <td>DESTINATION</td>
    <td>NUM OF SEATS</td>
    <td>PRICE</td>
    <td>DATE</td>
    <td>TIME</td>
    <td>STATUS</td>
  </thead>

  {% for row in book_list %}
  <tr>
    <td>{{row.id}}</td>
    <td>{{row.name}}</td>
    <td>{{row.bus_name}}</td>
    <td>{{row.source}}</td>
    <td>{{row.dest}}</td>
    <td>{{row.nos}}</td>
    <td>{{row.price}}</td>
    <td>{{row.date}}</td>
    <td>{{row.time}}</td>
    <td>{{row.status}}</td>
  </tr>
  {% endfor %}
</table>
<form action="{% url 'myapp:cancellings' %}" method="post">
  <h3>Choose bus to cancel book</h3>
  {% csrf_token %}
  <div class="col-auto">
    <label for="example-email-input" class="col-2 col-form-label"
      >Book ID</label
    >
    <div class="col-5">
      <input
        name="bus_id"
        class="form-control"
        type="number"
        id="example-email-input"
      />
    </div>
  </div>

  <br />
  <br />
  <div class="pull-right">
    <button type="submit" class="btn btn-danger float-left">Cancel bus</button>
  </div>

  {{error}}
</form>

{% endblock %}

bus-reservation-system-in-django/myproject/myapp/templates/myapp/error.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="container">
        <div class="row">
            <div class="col-sm-6 mx-auto" style="margin-top: 70px">
                <h1>{{error}}</h1>
            </div>
        </div>

    </div>

{% endblock %}

bus-reservation-system-in-django/myproject/myapp/templates/myapp/findbus.html
{% extends 'myapp/base.html' %} {% load static %} {% block content %}
<style>
  body {
    background-image: url("{% static 'myapp/FindBus.jpg' %}");
    background-size: cover;
    background-position: center;
  }

  .transparent-form {
    background-color: rgba(255, 255, 255, 0.8);
    padding: 50px;
    margin-top: 100px;
    animation: fadeInUp 1s ease-in;
    height: 400px;
    width: 400px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
  }

  footer {
    color: silver;
    margin-top: 500px;
  }

  @keyframes fadeInUp {
    0% {
      opacity: 0;
      transform: translateY(-50px);
    }
    100% {
      opacity: 1;
      transform: translateY(0);
    }
  }
</style>

<div class="container">
  <div class="row">
    <div class="col-sm-6 mx-auto transparent-form">
      <h2 class="animate__animated animate__fadeIn" style="margin-bottom: 10px">
        Find bus
      </h2>
      <form
        action="{% url 'myapp:findbus' %}"
        method="post"
        class="animate__animated animate__fadeIn"
      >
        {% csrf_token %}
        <div class="form-group row animate__animated animate__fadeIn">
          <label for="source" class="col-4 col-form-label">From</label>
          <div class="col-8">
            <select
              name="source"
              id="source"
              class="form-control"
              style="margin-bottom: 10px"
            >
              <option value="DebreMarkos">Debre Markos</option>
              <option value="BahirDar">Bahir Dar</option>
              <option value="Gondar">Gondar</option>
              <option value="DebreTabor">Debre Tabor</option>
              <option value="DebreBerhan">Debre Berhan</option>
              <option value="DebreWerq">Debre Werq</option>
              <option value="Dejen">Dejen</option>
              <option value="Dessie">Dessie</option>
              <option value="Kombolcha">Kombolcha</option>
              <option value="AddisAbaba">Addis Ababa</option>
              <!-- Add more options as needed -->
            </select>
          </div>
        </div>
        <div class="form-group row animate__animated animate__fadeIn">
          <label for="destination" class="col-4 col-form-label"
            >Destination</label
          >
          <div class="col-8">
            <select
              name="destination"
              id="destination"
              class="form-control"
              style="margin-bottom: 10px"
            >
              <option value="DebreMarkos">Debre Markos</option>
              <option value="BahirDar">Bahir Dar</option>
              <option value="Gondar">Gondar</option>
              <option value="DebreTabor">Debre Tabor</option>
              <option value="DebreBerhan">Debre Berhan</option>
              <option value="DebreWerq">Debre Werq</option>
              <option value="Dejen">Dejen</option>
              <option value="Dessie">Dessie</option>
              <option value="Kombolcha">Kombolcha</option>
              <option value="AddisAbaba">Addis Ababa</option>
              <!-- Add more options as needed -->
            </select>
          </div>
        </div>
        <div class="form-group row animate__animated animate__fadeIn">
          <label for="date" class="col-4 col-form-label">Date</label>
          <div class="col-8">
            <input name="date" class="form-control" type="date" />
          </div>
        </div>
        <div class="pull-right animate__animated animate__fadeIn">
          <button
            type="submit"
            class="btn btn-success float-right"
            style="margin-top: 10px"
          >
            Find bus
          </button>
        </div>
        {{ error }}
      </form>
    </div>
  </div>
</div>

{% endblock %}

bus-reservation-system-in-django/myproject/myapp/templates/myapp/list.html
{% extends 'myapp/base.html' %} {% block content %}
<h3>{{ msg }}</h3>
<h2>List of buses</h2>
<table class="table table-striped">
  <thead style="background-color: blue; color: white">
    <td>ID</td>
    <td>NAME</td>
    <td>SOURCE</td>
    <td>DESTINATION</td>
    <td>NUM OF SEATS</td>
    <td>NUM OF SEATS REM</td>
    <td>PRICE</td>
    <td>DATE</td>
    <td>TIME</td>
  </thead>

  {% for row in bus_list %}
  <tr>
    <td>{{ row.id }}</td>
    <td>{{ row.bus_name }}</td>
    <td>{{ row.source }}</td>
    <td>{{ row.dest }}</td>
    <td>{{ row.nos }}</td>
    <td>{{ row.rem }}</td>
    <td>{{ row.price }}</td>
    <td>{{ row.date }}</td>
    <td>{{ row.time }}</td>
    <td>{{ row.tid }}</td>
  </tr>
  {% endfor %}
</table>
<form
  action="{% url 'myapp:bookings' %}"
  method="post"
  enctype="multipart/form-data"
>
  <h3>Choose bus to book</h3>
  {% csrf_token %}
  <div class="col-auto">
    <label for="example-email-input" class="col-2 col-form-label">Bus ID</label>
    <div class="col-5">
      <input
        name="bus_id"
        class="form-control"
        type="number"
        id="example-email-input"
      />
    </div>
  </div>
  <div class="col-auto">
    <label for="example-email-input" class="col-2 col-form-label"
      >Number Of Seats</label
    >
    <div class="col-5">
      <input name="no_seats" class="form-control" type="number" />
    </div>
  </div>
  <div class="col-auto">
    <label for="itransaction_id" class="col-2 col-form-label"
      >Transaction Id</label
    >
    <div class="col-5">
      <input
        name="itransaction_id"
        class="form-control"
        type="text"
        id="itransaction_id"
        pattern="[0-9]+"
        title="Please enter a valid number"
        required
      />
    </div>
  </div>
  <div class="col-auto">
    <label for="itransaction_image" class="col-2 col-form-label"
      >Transaction Image</label
    >
    <div class="col-5">
      <input
        name="itransaction_image"
        class="form-control-file"
        type="file"
        accept="image/*"
        required
      />
    </div>
  </div>
  <br />
  <br />
  <div class="pull-right">
    <button type="submit" class="btn btn-success float-left">Book bus</button>
  </div>

  {{ error }}
</form>

{% endblock %}

bus-reservation-system-in-django/myproject/myapp/templates/myapp/signin.html
{% extends 'myapp/base.html' %} {% load static %} {% block content %}

<style>
  body {
    background-image: url("{% static 'myapp/login.png' %}");
    background-size: cover;
    background-position: center;
  }

  .transparent-form {
    background-color: rgba(255, 255, 255, 0.8);
    padding: 20px;
    margin-top: 70px;
    animation: fadeIn 1s ease-in;
  }

  footer {
    color: white;
    margin-top: 100px;
  }

  @keyframes fadeIn {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
</style>
<div class="container">
  <div class="row">
    <div class="col-sm-6 mx-auto transparent-form">
      <h2 class="animate__animated animate__fadeIn">Login</h2>
      <form
        action="{% url 'myapp:signin' %}"
        method="POST"
        class="animate__animated animate__fadeIn"
      >
        {% csrf_token %}
        <div class="form-group row">
          <label for="example-email-input" class="col-2 col-form-label"
            >Username:</label
          >
          <div class="col-10">
            <input
              name="name"
              class="form-control"
              type="text"
              id="example-email-input"
            />
          </div>
        </div>
        <div class="form-group row">
          <label for="example-email-input" class="col-2 col-form-label"
            >Password:</label
          >
          <div class="col-10">
            <input name="password" class="form-control" type="password" />
          </div>
        </div>
        <div class="pull-right">
          <button type="submit" class="btn btn-primary float-right">
            Sign In
          </button>
        </div>
        {{ error }}
      </form>
      <p class="animate__animated animate__fadeIn">
        Don't have an account? <a href="{% url 'myapp:signup' %}">Sign up</a>
      </p>
    </div>
  </div>
</div>
{% endblock %}

bus-reservation-system-in-django/myproject/myapp/templates/myapp/success.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="container">
        <div class="row">
            <div class="col-sm-6 mx-auto" style="margin-top: 70px">
                <form action="{% url 'myapp:signout' %}" method="post">
                    {% csrf_token %}
                    {{user}} successful login! {{id}}


                    <div class="pull-right">
                        <button type="Submit" class="btn btn-success float-right">Sign out</button>
                    </div>

                </form>
            </div>
        </div>

    </div>
{% endblock %}

bus-reservation-system-in-django/myproject/myapp/templates/myapp/thank.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="container">
        <div class="row">
            <div class="col-sm-6 mx-auto" style="margin-top: 70px">
                <h1>Thank you for signing up!</h1>
            </div>
        </div>

    </div>

{% endblock %}